/**
 * Type definitions for Durable Objects browser session pooling
 */

import type { Browser } from '@cloudflare/puppeteer';

/**
 * Durable Object state representing a browser session pool
 */
export interface BrowserPoolState {
  /** Unique identifier for this Durable Object instance */
  objectId: string;
  /** Array of active browser instances in the pool */
  browserInstances: BrowserInstance[];
  /** Queue of pending PDF generation requests */
  requestQueue: QueuedRequest[];
  /** Timestamp when this Durable Object was created */
  createdAt: Date;
  /** Timestamp of last activity (request processed or browser action) */
  lastActivityAt: Date;
  /** Total number of PDFs generated by this pool since creation */
  totalPdfsGenerated: number;
  /** Current load (number of in-flight requests) */
  currentLoad: number;
}

/**
 * Represents a single Chrome browser instance in the pool
 */
export interface BrowserInstance {
  /** Unique identifier for this browser instance */
  instanceId: string;
  /** Reference to the @cloudflare/puppeteer Browser object */
  browserHandle: Browser | null;
  /** Timestamp when this browser was launched */
  createdAt: Date;
  /** Number of PDFs generated by this browser instance */
  pdfsGenerated: number;
  /** Timestamp of last PDF generation using this browser */
  lastUsedAt: Date;
  /** Estimated memory usage in megabytes */
  memoryUsage: number;
  /** Current status of the browser instance */
  status: 'active' | 'idle' | 'crashed';
}

/**
 * Represents a queued PDF generation request waiting for an available browser
 */
export interface QueuedRequest {
  /** Unique identifier for this request */
  requestId: string;
  /** User ID making the request (for routing) */
  userId: string;
  /** HTML content to render as PDF */
  html: string;
  /** PDF generation options */
  options: PdfOptions;
  /** Timestamp when request was queued */
  timestamp: Date;
  /** Priority level (higher = processed first) */
  priority: number;
}

/**
 * PDF generation options (subset of Puppeteer PDF options)
 */
export interface PdfOptions {
  /** Paper format (e.g., 'A4', 'Letter', 'Legal') */
  format?: string;
  /** Print background graphics */
  printBackground?: boolean;
  /** Scale of webpage rendering (0.1 to 2) */
  scale?: number;
  /** Paper orientation */
  landscape?: boolean;
  /** Page margins */
  margin?: {
    top?: string;
    right?: string;
    bottom?: string;
    left?: string;
  };
  /** Display header and footer */
  displayHeaderFooter?: boolean;
  /** Header template */
  headerTemplate?: string;
  /** Footer template */
  footerTemplate?: string;
  /** User's pricing tier for R2 lifecycle tagging (free, starter, pro, enterprise) */
  userTier?: string;
  /** User ID for metadata and tracking */
  userId?: string;
}

/**
 * Result of a PDF generation request
 */
export interface PdfResult {
  /** Whether the PDF was generated successfully */
  success: boolean;
  /** URL to the generated PDF (if successful) */
  pdfUrl?: string;
  /** ISO 8601 timestamp when the PDF will expire and be deleted */
  expiresAt?: string;
  /** Time taken to generate the PDF in milliseconds */
  generationTime: number;
  /** Error message (if failed) */
  error?: string;
  /** Request ID for tracking */
  requestId: string;
}

/**
 * A single job in a batch PDF generation request
 */
export interface PdfJob {
  /** Unique identifier for this job within the batch */
  jobId: string;
  /** HTML content to render */
  html: string;
  /** PDF generation options */
  options: PdfOptions;
}

/**
 * Metadata for an active Cap'n Web RPC session
 */
export interface RpcSessionMetadata {
  /** Unique session identifier */
  sessionId: string;
  /** User ID (null for unauthenticated demo requests) */
  userId: string | null;
  /** Connection type (HTTP Batch or WebSocket) */
  connectionType: 'http-batch' | 'websocket';
  /** Timestamp when session started */
  startedAt: Date;
  /** Timestamp of last heartbeat ping/pong */
  lastHeartbeat: Date;
  /** Total number of RPC requests in this session */
  requestCount: number;
}

/**
 * Pricing tier configuration
 */
export interface PricingTierConfig {
  /** Plan tier name */
  tier: 'free' | 'starter' | 'pro' | 'enterprise';
  /** Monthly price in USD */
  monthlyPrice: number;
  /** Monthly PDF generation quota */
  pdfQuota: number;
  /** PDF retention period in days */
  retentionDays: number;
  /** Rate limit (requests per minute) */
  rateLimitPerMinute: number;
}

/**
 * R2 lifecycle policy rule
 */
export interface R2LifecycleRule {
  /** Unique rule identifier */
  ruleId: string;
  /** Filter criteria for objects */
  filter: {
    /** Tag-based filtering */
    tags: { key: string; value: string };
  };
  /** Expiration configuration */
  expiration: {
    /** Number of days until expiration */
    days: number;
  };
  /** Whether this rule is active */
  enabled: boolean;
}
