/**
 * Script to create a test user and API key for local development
 *
 * This script:
 * 1. Creates a test user in the database
 * 2. Generates a test API key
 * 3. Prints the API key for use in testing
 *
 * Run with: npx tsx scripts/create-test-user.ts
 */

import { createClient } from '@supabase/supabase-js';
import crypto from 'crypto';
import * as dotenv from 'dotenv';
import * as path from 'path';

// Load environment variables from .env.local
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

// Environment variables (loaded from .env.local)
const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

// Crypto utilities (Node.js versions)
function generateApiKey(environment: 'live' | 'test' = 'test'): string {
  const randomBytes = crypto.randomBytes(32);
  const randomHex = randomBytes.toString('hex');
  const prefix = environment === 'live' ? 'sk_live_' : 'sk_test_';
  return prefix + randomHex;
}

function hashApiKey(apiKey: string): string {
  return crypto.createHash('sha256').update(apiKey).digest('hex');
}

function extractApiKeyMetadata(apiKey: string) {
  const prefix = apiKey.substring(0, 8);
  const last4 = apiKey.substring(apiKey.length - 4);
  const environment = apiKey.startsWith('sk_live_') ? 'live' : 'test';
  return { prefix, last4, environment };
}

async function main() {
  console.log('🚀 Creating test user and API key...\n');

  // Initialize Supabase client
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  // Test user details
  const testUser = {
    email: 'test@speedstein.dev',
    password_hash: crypto.createHash('sha256').update('TestPassword123!').digest('hex'),
    name: 'Test User',
  };

  try {
    // Check if user already exists
    const { data: existingUser } = await supabase
      .from('users')
      .select('id, email')
      .eq('email', testUser.email)
      .single();

    let userId: string;

    if (existingUser) {
      console.log('✅ Test user already exists:', existingUser.email);
      userId = existingUser.id;
    } else {
      // Create new user
      const { data: newUser, error: userError } = await supabase
        .from('users')
        .insert(testUser)
        .select('id, email')
        .single();

      if (userError) {
        throw new Error(`Failed to create user: ${userError.message}`);
      }

      console.log('✅ Created test user:', newUser.email);
      userId = newUser.id;
    }

    // Check if API key already exists
    const { data: existingKeys } = await supabase
      .from('api_keys')
      .select('*')
      .eq('user_id', userId)
      .eq('name', 'Test API Key')
      .eq('revoked', false);

    if (existingKeys && existingKeys.length > 0) {
      console.log('\n⚠️  Test API key already exists for this user.');
      console.log('Please use the existing key or manually revoke it in the database.\n');
      console.log('To revoke: UPDATE api_keys SET revoked = true WHERE id = \'' + existingKeys[0].id + '\';');
      return;
    }

    // Generate new API key
    const apiKey = generateApiKey('test');
    const keyHash = hashApiKey(apiKey);
    const metadata = extractApiKeyMetadata(apiKey);

    // Insert API key into database
    const { data: newApiKey, error: keyError } = await supabase
      .from('api_keys')
      .insert({
        user_id: userId,
        key_hash: keyHash,
        prefix: metadata.prefix,
        last4: metadata.last4,
        name: 'Test API Key',
        revoked: false,
      })
      .select('*')
      .single();

    if (keyError) {
      throw new Error(`Failed to create API key: ${keyError.message}`);
    }

    console.log('✅ Created test API key\n');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('🔑 YOUR TEST API KEY (save this, it won\'t be shown again):');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(apiKey);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    console.log('📝 Test this API key with:');
    console.log(`
curl http://127.0.0.1:8787/api/generate \\
  -H "Authorization: Bearer ${apiKey}" \\
  -H "Content-Type: application/json" \\
  -d '{
    "html": "<html><body><h1>Test PDF</h1><p>This is a test PDF generated by Speedstein.</p></body></html>",
    "options": {
      "format": "A4",
      "margin": {
        "top": "1cm",
        "right": "1cm",
        "bottom": "1cm",
        "left": "1cm"
      }
    }
  }'
`);

    console.log('\n✅ Setup complete! You can now test the API.');
  } catch (error) {
    console.error('❌ Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

main();
